"""Add category, visibility, tags, likes_count, views_count to posts

Revision ID: dc89dc7375c6
Revises: cbe506274b63
Create Date: 2025-07-18 15:02:07.010183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc89dc7375c6'
down_revision = 'cbe506274b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('views_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_likes_count'), ['likes_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_views_count'), ['views_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_visibility'), ['visibility'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_visibility'))
        batch_op.drop_index(batch_op.f('ix_posts_views_count'))
        batch_op.drop_index(batch_op.f('ix_posts_likes_count'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_posts_category'))
        batch_op.drop_column('views_count')
        batch_op.drop_column('likes_count')
        batch_op.drop_column('tags')
        batch_op.drop_column('visibility')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
